
#include "output_test.h"
#include "output_test.c"
#include "../util/data_structs.h"

int main() {

	output_layer_test(OUTPUT_LAYER_1_TEST_INPUT_DATA, OUTPUT_LAYERS_TEST_GOLDEN, OUTPUT_LAYER_1_OUTPUT, POSSBILE_CHARACTERS_DATA, 1);
	output_layer_test(OUTPUT_LAYER_2_TEST_INPUT_DATA, OUTPUT_LAYERS_TEST_GOLDEN, OUTPUT_LAYER_2_OUTPUT, POSSBILE_CHARACTERS_DATA, 2);
	output_layer_test(OUTPUT_LAYER_3_TEST_INPUT_DATA, OUTPUT_LAYERS_TEST_GOLDEN, OUTPUT_LAYER_3_OUTPUT, POSSBILE_CHARACTERS_DATA, 3);
	output_layer_test(OUTPUT_LAYER_4_TEST_INPUT_DATA, OUTPUT_LAYERS_TEST_GOLDEN, OUTPUT_LAYER_4_OUTPUT, POSSBILE_CHARACTERS_DATA, 4);
	output_layer_test(OUTPUT_LAYER_5_TEST_INPUT_DATA, OUTPUT_LAYERS_TEST_GOLDEN, OUTPUT_LAYER_5_OUTPUT, POSSBILE_CHARACTERS_DATA, 5);


	return 0;
}